# Generated by Django 5.2 on 2025-04-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='messsage',
            new_name='message',
        ),
    ]
